version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/usr/share/nginx/html/public:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
